テストを追加

diff --git a/Bash/Tests/RUNTEST-convert b/Bash/Tests/RUNTEST-convert
--- a/Bash/Tests/RUNTEST-convert
+++ b/Bash/Tests/RUNTEST-convert
@@ -7,6 +7,7 @@ test_data_dir="${test_work_dir}"
 
 pushd "${test_work_dir}"
 
+# CSV
 cat "${test_data_dir}/input.csv"  \
     | gawk -F ',' -f ../convert.awk -v tablename=Sheet1  \
     > content.body.xml
@@ -16,5 +17,21 @@ diff -s content.body.xml content.body.OUT || ret=$?
 
 if [[ ${ret} -ne 0 ]] ; then
     echo -e "\033[1;31;102;5mTest FAILURE!!\033[0m"
+    popd
+    exit ${ret}
 fi
+
+# TSV
+cat "${test_data_dir}/../sample.tsv"  \
+    | gawk -F '\t' -f ../convert.awk -v tablename=Sheet1  \
+    > content.body.xml
+
+ret=0
+diff -s content.body.xml content.body.OUT || ret=$?
+
+if [[ ${ret} -ne 0 ]] ; then
+    echo -e "\033[1;31;102;5mTest FAILURE!!\033[0m"
+fi
+
+popd
 exit ${ret}
